# Generated by Django 5.2.6 on 2025-09-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del estado (ej: PENDING, PAID, CANCELLED)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del estado', null=True)),
                ('es_estado_final', models.BooleanField(default=False, help_text='Indica si es un estado final (no permite cambios posteriores)')),
                ('permite_reembolso', models.BooleanField(default=False, help_text='Indica si permite solicitar reembolso')),
                ('color_hex', models.CharField(default='#6c757d', help_text='Color para mostrar en interfaz (formato hex: #RRGGBB)', max_length=7)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden para mostrar en listas')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el estado está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Compra',
                'verbose_name_plural': 'Estados de Compra',
                'db_table': 'estados_compra',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del tipo de documento (ej: RUT, CC, PA)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de documento', max_length=50)),
                ('formato_validacion', models.CharField(blank=True, help_text='Expresión regular para validar el formato del documento', max_length=100, null=True)),
                ('longitud_minima', models.PositiveSmallIntegerField(default=1, help_text='Longitud mínima del número de documento')),
                ('longitud_maxima', models.PositiveSmallIntegerField(default=20, help_text='Longitud máxima del número de documento')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de documento está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipos_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la categoría', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen representativa de la categoría', null=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión para esta categoría', max_digits=5)),
                ('requiere_garantia', models.BooleanField(default=False, help_text='Indica si los productos de esta categoría requieren garantía')),
                ('dias_garantia_defecto', models.PositiveIntegerField(default=30, help_text='Días de garantía por defecto para productos de esta categoría')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la categoría está activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden para mostrar en listas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria_padre', models.ForeignKey(blank=True, help_text='Categoría padre (para jerarquías)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='clientes.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'db_table': 'categorias_producto',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['categoria_padre'], name='categorias__categor_a0fa09_idx'), models.Index(fields=['activo', 'orden'], name='categorias__activo_9d29ae_idx')],
            },
        ),
    ]
