# Generated by Django 5.2.6 on 2025-09-27 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número de documento de identificación', max_length=50)),
                ('nombre', models.CharField(help_text='Nombre(s) del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido(s) del cliente', max_length=100)),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, help_text='Número telefónico del cliente', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 20 caracteres y puede incluir +, espacios, guiones y paréntesis', regex='^[\\+]?[0-9\\s\\-\\(\\)]{7,20}$')])),
                ('direccion', models.TextField(blank=True, help_text='Dirección residencial del cliente', null=True)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad de residencia', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, help_text='Departamento o estado de residencia', max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal', max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del cliente', null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], help_text='Género del cliente', max_length=1, null=True)),
                ('acepta_marketing', models.BooleanField(default=False, help_text='Indica si el cliente acepta recibir comunicaciones de marketing')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo en el sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización')),
                ('total_compras', models.DecimalField(decimal_places=2, default=0.0, help_text='Total acumulado de todas las compras del cliente', max_digits=15)),
                ('numero_compras', models.PositiveIntegerField(default=0, help_text='Número total de compras realizadas')),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, help_text='Fecha de la última compra realizada', null=True)),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento de identificación del cliente', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.tipodocumento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_creacion', 'apellido', 'nombre'],
                'indexes': [models.Index(fields=['tipo_documento', 'numero_documento'], name='idx_cliente_documento'), models.Index(fields=['correo'], name='idx_cliente_correo'), models.Index(fields=['telefono'], name='idx_cliente_telefono'), models.Index(fields=['activo', 'fecha_creacion'], name='idx_cliente_activo_fecha'), models.Index(fields=['total_compras'], name='idx_cliente_total_compras'), models.Index(fields=['fecha_ultima_compra'], name='idx_cliente_ultima_compra')],
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_cliente_documento')],
            },
        ),
    ]
