# Generated by Django 5.2.6 on 2025-09-27 20:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de factura', max_length=50, unique=True)),
                ('fecha_compra', models.DateTimeField(help_text='Fecha y hora en que se realizó la compra')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal antes de descuentos e impuestos', max_digits=15)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de descuentos aplicados', max_digits=15)),
                ('iva_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de IVA aplicado', max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de la compra', max_digits=15)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales de la compra', null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('TRANSFERENCIA', 'Transferencia Bancaria')], help_text='Método de pago utilizado', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que realizó la compra', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.cliente')),
                ('estado', models.ForeignKey(help_text='Estado actual de la compra', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.estadocompra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (SKU)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del producto (sin descuentos ni impuestos)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicable (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA aplicable (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='Stock mínimo para alertas de reposición')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso del producto en kilogramos', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('dimensiones', models.CharField(blank=True, help_text='Dimensiones del producto (ej: 10x15x20 cm)', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, help_text='Marca del producto', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo para la venta')),
                ('destacado', models.BooleanField(default=False, help_text='Indica si el producto está destacado en el catálogo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='clientes.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del producto comprado', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la compra (sin descuentos ni IVA)', max_digits=12)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total aplicado a este producto', max_digits=12)),
                ('iva_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA total aplicado a este producto', max_digits=12)),
                ('subtotal_producto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal final calculado para este producto', max_digits=15)),
                ('descuento_porcentaje_momento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento que tenía el producto al momento de la compra', max_digits=5)),
                ('iva_porcentaje_momento', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA que tenía el producto al momento de la compra', max_digits=5)),
                ('compra', models.ForeignKey(help_text='Compra a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes.compra')),
                ('producto', models.ForeignKey(help_text='Producto incluido en la compra', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='clientes.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'detalles_compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['cliente', 'fecha_compra'], name='idx_compra_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado'], name='idx_compra_estado'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['numero_factura'], name='idx_compra_factura'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fecha_compra'], name='idx_compra_fecha'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['monto_total'], name='idx_compra_monto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='idx_producto_categoria_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='idx_producto_codigo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='idx_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio_base'], name='idx_producto_precio'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='idx_producto_stock'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado', 'activo'], name='idx_producto_destacado'),
        ),
        migrations.AddIndex(
            model_name='detallecompra',
            index=models.Index(fields=['compra'], name='idx_detalle_compra'),
        ),
        migrations.AddIndex(
            model_name='detallecompra',
            index=models.Index(fields=['producto'], name='idx_detalle_producto'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.UniqueConstraint(fields=('compra', 'producto'), name='unique_compra_producto'),
        ),
    ]
